key_name     = "key-bucket"
keyring_name = "keyring-bucket"
region       = "us-central1"
bucket_name  = "df-storage"
host_project = "my-host-project-356917"
project = "my-service-project-357012"
service_project = "my-service-project-357012"
